### ISSUE TITLE
Question about dataset SE1415

### ISSUE THREAD

**Issue by hmt2014** [vanzytay/ABSA_DevSplits#2]
I have question about the polarity label in SE1415, the polarities are numbered by 1, 2, 3, 4. 
1 is neg, 2 is pos, 3 is neu
but what is 4 represents? And there are lots of samples that are labeled 4.

**Comment by vanzytay** [comment]
Hi. I obtained this dataset from Cheng Li's memory network paper in WSDM. (https://arxiv.org/abs/1701.04189)

4 represented no-aspect found. this is not used in our paper.

**Comment by hmt2014** [comment]
Thank you !

**Comment by hmt2014** [comment]
Hello, I have one question.
I am writing paper and uses the same dataset as you in your AF-LSTM paper.
And I will cite your paper.
I do not know whether i can copy the dataset information to my paper. The dataset information includes the number of each dataset and each kind of label.

Best Regards

At 2018-07-23 15:51:41, "Yi Tay" <notifications@github.com> wrote:


Hi. I obtained this dataset from Cheng Li's memory network paper in WSDM. (https://arxiv.org/abs/1701.04189)

4 represented no-aspect found. this is not used in our paper.

**Comment by vanzytay** [comment]
hi!

The dataset table in the paper is _mostly correct_ but someone has pointed to me to a  wrong value in the table (it was like one or two columns were swapped by accident). Due to being too busy I have yet to update the arxiv version of the paper with this errata. 

It is better if you report the statistics from the files here, to avoid any misunderstanding.

**Comment by hmt2014** [comment]
Ok!
Thank you very much!
